# Compressed:
#
DATASET:
    NAME: "transparenturodata_boundary"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 1
    CROP_SIZE: (400, 400)
    BASE_SIZE: 400
    ROI_START: (100,192)
    ROI_END: (308,400)
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/trans2seg_tiny'
    DATA_ROOT: '/Users/longquanchen/Desktop/Work/DeepLearning/Segment_Transparent_Objects/datasets/laserfiberBigData/SelectedVidsPostBlender'
TEST:
    BATCH_SIZE: 16
    CROP_SIZE: (400, 400)
    DATA_ROOT: '/Users/longquanchen/Desktop/Work/DeepLearning/Segment_Transparent_Objects/datasets/laserfiberBigData/SelectedVidsPostBlender'
    TEST_MODEL_PATH: '/Users/longquanchen/Desktop/Work/DeepLearning/Trans2Seg/tools/workdirs/trans10kv2/trans2seg_mobilenet_ROI/46.pth'
    ROI_START: (100,192)
    ROI_END: (308,400)
SOLVER:
    OPTIMIZER: "adam"
    LR: 0.0001
MODEL:
    MODEL_NAME: "TransLab"
    BACKBONE: "mobilenet_v2" #"resnet50c"
    TRANS2Seg:
        embed_dim: 128
        depth: 1
        num_heads: 4
        mlp_ratio: 2.
        hid_dim: 32
    DEEPLABV3_PLUS.USE_ASPP : False

AUG:
    CROP: False